FROM debian:trixie
RUN dpkg --add-architecture arm64

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    build-essential \
    crossbuild-essential-arm64 \
    golang-go \
    pkg-config \
    # Install target arm64 libraries here
    libsdl2-dev:arm64 \
    libxkbcommon-dev:arm64 \
    && rm -rf /var/lib/apt/lists/*

ENV CGO_ENABLED=1
ENV GOOS=linux
ENV GOARCH=arm64

ENV CC=aarch64-linux-gnu-gcc
ENV CXX=aarch64-linux-gnu-g++

ENV PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkg-config/
ENV PKG_CONFIG_ALLOW_CROSS=1

WORKDIR /build
